Fix workspace definitions (#12)
305ca5a switched from homepage to repository in the workspace Cargo.toml file, but not in the Cargo.toml files of the sub-crates, causing them to not build:

error: failed to load source for dependency `egm96`

Caused by:
  Unable to update <my project>\external\egm96-rs\egm96

Caused by:
  failed to parse manifest at `<my project>\external\egm96-rs\egm96\Cargo.toml`

Caused by:
  error inheriting `homepage` from workspace root manifest's `workspace.package.homepage`

Caused by:
  `workspace.package.homepage` was not defined